### ISSUE TITLE
[dep-check] Rename of rnx-kit config key

### ISSUE THREAD

**Issue by AlekhyaYalla** [microsoft/rnx-kit#1093]
The dep-check configuration in any package.json is referred to by the key "rnx-kit" which might be obtuse and not describe the functionality we are taking via config.
Can we rename it to keep it more specific to the dep-check tool? 
Suggestion:  "dep-check" 

Also the "customProfiles" key in the config, takes the path of the custom profile. Can it also be renamed to make its functionality understandable to anyone who's using the config?

These are my suggestions, please feel free to make them more meaningful.
``` 
"dep-check": {
      "capabilities": [
         "bundle-capabilities"
      ],
      "profiles": "my-custom-profiles"
  }
```

**Comment by bweggersen** [comment]
I believe such a change could lower the barrier to introduce `dep-check` to an existing repo. I think a more generic key could also be considered, such as `dependencyManagementConfig`.

**Comment by tido64** [comment]
Just to give a bit more context: We have a tool called `@rnx-kit/cli` that provides a command line interface for all the tools we build in this repo. We use `rnx-kit` as the namespace for configuring all the commands such as bundling, starting the dev server, etc. including `@rnx-kit/dep-check`. `@rnx-kit/dep-check` is a bit special here because it is also standalone.

Given its ties with `@rnx-kit/cli`, I don't think it makes any sense to rename the config key. That would essentially break configuration of other commands.

An alternative that was proposed would be to **_add_** a new key just for `@rnx-kit/dep-check`. In general, I'm opposed to adding a second way to configure the same thing. I think adds more confusion and ambiguity. From the user's perspective, how can they tell which custom profiles are being applied below?

```json
{
  "@rnx-kit/dep-check": {
    "profiles": "my-custom-profiles"
  },
  "rnx-kit": {
    "profiles": "my-other-custom-profiles"
  }
}
```

It also looks like they have to put some config under `"@rnx-kit/dep-check"` and others under `"rnx-kit"`.

Further, as we evolve `@rnx-kit/cli` and add more tools in the repo, we want to be able to leverage the same configuration for other purposes. For instance, service delivery can use the capabilities list to determine whether an app can host a feature, or build-tools can automatically exclude native modules of unused app capabilities. `@rnx-kit/dep-check` only plays one part in an eco-system of tools, so I believe we need to think about how it affects the whole rather than looking at one tool in isolation.

Pinging @afoxman and @JasonVMo for their views.

**Comment by afoxman** [comment]
Nothing to add. @tido64 covered it all. dep-check may be standalone, but its config is a piece of the larger config landscape.
