### ISSUE TITLE
obey `save-prefix`

### ISSUE THREAD

**Issue by pvinis** [microsoft/rnx-kit#1470]
### What happened?

i run the dep check with `--write`, and it added things like `^1.2.3`, but in our repo we like to use `save-prefix ""`, so all deps are pinned.

is it possible to keep this?

### Affected Package

@rnx-kit/dep-check

### Version

1.12.13

### Which platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [X] macOS
- [ ] Windows

### System Information

```true
info Fetching system and libraries information...
System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 66.16 MB / 16.00 GB
    Shell: 5.8.1 - /usr/local/bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.asdf/installs/nodejs/16.10.0/bin/node
    Yarn: 1.22.10 - ~/.asdf/shims/yarn
    npm: 7.24.0 - ~/.asdf/installs/nodejs/16.10.0/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/pavlos/.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 26, 29, 30, 31
      Build Tools: 26.0.3, 28.0.3, 29.0.2, 30.0.2, 31.0.0, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /Users/pavlos/.asdf/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.66.0-0 => 0.66.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

run `yarn rnx-dep-check --write`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Hi @pvinis, thanks for filing this issue. I'm sure you're aware of the scenarios we're trying to support, but just to make sure l everyone is on the same page: We treat the version number declared in the profiles as truth for a number of reasons.

We use caret (^) and tilde (~) in most cases to ensure that users can still bump if necessary without having to wait for a new dep-check version. Either because they need a bug fix or because of security issues. For certain packages, like `react`, we pin the version.

As a consequence, we don't update our profiles as often when we use `^`. Most often, we will only bump a package if we deem it necessary. For instance we recently bumped `react-native-reanimated` because it wouldn't work with latest react-native version otherwise. For `react-native`, we likely won't touch it after a profile has been created.

In some scenarios, we cannot go any higher because of build breaks. If you look at the profile for 0.64, the version is set to 0.64.2: https://github.com/microsoft/rnx-kit/blob/8ee836b9a8f3977ee687ed53a9b3eac42de768e8/packages/dep-check/src/profiles/profile-0.64.ts#L5-L6

But the latest 0.64 is `.3`. This allows the one app that breaks on `.3` to still use `.2` while others can use the latest version. Note that profiles past 0.64 all declare `.0`.

Going back go your suggestion to obey `save-prefix`: I am aware that people have started using this more to mitigate supply chain attacks. Regardless, I have a number of questions around how to support this without degrading the UX for the scenarios outlined above:

- How do we apply `save-prefix`?
  - For the `""` case, do we remove all specifiers?
  - What do we do if it is set to something else, like `~`?
    - The answer to this is probably only swap out `^` when set to `~`, and keep the rest.
- If we remove all specifiers, are we fine with `react-native` being pinned to `.0` by default?
- What do we expect users to do if they need to bump a package?

In my mind, the answer to the last two questions is to create a custom profile. But since you already have to create one to support the pinned versions scenario, why not just declare all explicit versions here?

Curious to hear your opinion. Maybe I'm just missing something super obvious 😄
