### ISSUE TITLE
RNX Kit can't find my library to update

### ISSUE THREAD

**Issue by lfoliveir4** [microsoft/rnx-kit#1621]
### What happened?

I'm starting to use the RNX Kit to update the dependencies of some of my personal projects. So, I wanted to understand the following message that rnx-kit shows in my terminal when I put a dependency in the `capabilities` array.

`The following capabilities could not be resolved for one or more profiles: react-native-camera`

`The following capabilities could not be resolved for one or more profiles: camera`

In case, I'm trying to update the `react-native-camera` library. What does this message mean? Am I doing something wrong or is rnx-kit unable to identify this library? If it doesn't see this library, what are the steps for rnx-kit to be able to identify this library?

### Affected Package

react-native-camera

### Version

^3.18.0

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [X] macOS
- [ ] Windows

### System Information

```true
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 100.83 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 7.10.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

I tried in two ways:

I added `camera` to my `capabilities` array in the `rnx-kit` object and tried to add `react-native-camera` to my `capabilities` array in the `rnx-kit` object

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kelset** [comment]
👋  @lfoliveir4 - thanks for opening this issue!

The issue here is that neither `camera` nor `react-native-camera` are capabilities that are available by default for rnx-kit; you can find the full list of default capabilities and packages [here](https://github.com/microsoft/rnx-kit/tree/main/packages/dep-check#capabilities).

In order to avoid to create this type of confusion in the future, I've also cooked up a quick PR for the docs to have more direct links to that table: https://github.com/microsoft/rnx-kit/pull/1631

That said, the way you can quickly address this in your local configuration is by adding a custom profile; you can read more [about it here](https://microsoft.github.io/rnx-kit/docs/guides/dependency-management#customization).
