### ISSUE TITLE
Multitple copies of a package flagged as error in console

### ISSUE THREAD

**Issue by itsramiel** [microsoft/rnx-kit#1942]
### What happened?

I followed the docs about setting up bundling, but when i run the rnx-bundle command I get an error about duplicate node_modules across my dependencies.

For example: 
```
error redux (found 2 copies)
warn   3.7.2 /Users/...node_modules/aws-appsync/node_modules/redux
warn   4.2.0 /Users/.../node_modules/redux
```

Isnt it normal for dependencies to depend on others.

What should I do in this case?

### Affected Package

"@rnx-kit/babel-preset-metro-react-native",  "@rnx-kit/cli", "@rnx-kit/metro-config", "@rnx-kit/metro-resolver-symlinks"

### Version

"^1.1.1",  "^0.14.8", "^1.3.1", "^0.1.21",

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 635.12 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.3 => 0.70.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
```


### Steps to Reproduce

just follow the docs guide in  a rn project with a lot dependencies

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Hi @itsramiel, you are getting this error because you have two different copies of `redux`. They are on different versions, which can be complicated to resolve. The first thing you need to do is to figure out which package is pulling them in, and why. Can you upgrade them so that the dependencies align? Failing that, can one of the packages use a downgraded/upgraded version of `redux`? If they can, you can follow the instructions here to force resolve them to a specific version: https://github.com/microsoft/rnx-kit/tree/main/packages/metro-config#ensuring-a-single-instance-of-a-package.
